### ISSUE TITLE
Unable to use Networking Beta ApiVersion in EKS Cluster

### ISSUE THREAD

**Issue by jensenity** [Hyper-Mesh/spark-history-server#9]
https://github.com/Hyper-Mesh/spark-history-server/blob/4d6ffbb038cfe18c9a19a928c2ca8315c559ccd4/stable/spark-history-server/templates/ingress.yaml#L2

Hi, I think the beta version has been deprecated. Is it possible to update it to v1?

https://stackoverflow.com/questions/72224230/error-resource-mapping-not-found-make-sure-crds-are-installed-first

**Comment by vara-bonthu** [comment]
Thanks for raising the issue! We can support multiple api versions based on k8s version. I will take a look. 

Happy for you to raise a PR if you have a working solution 👍

**Comment by jensenity** [comment]
@vara-bonthu thanks! I created a PR. :)
